### ISSUE TITLE
[BUG] Moulinette Core fails indexing scenes on certain filenames

### ISSUE THREAD

**Issue by OberstK** [SvenWerlen/moulinette-core#68] opened 2023-10-03 09:06 UTC
Error is:

Uncaught (in promise) URIError: undefined. URI malformed
[Detected 1 package: moulinette-core]
    at decodeURIComponent (<anonymous>)
    at MoulinetteFileUtil.updateIndex (moulinette-file-util.js:1227:37)
    at async MoulinetteSources._onAction (moulinette-sources.js:379:9)
    
Example of a file name it occurs on:

"Healing Pool - Hand-Painted Battle Map + 50% OFF my Foundry Tier_13m0094.jpg"

I think its because of the "%" but not sure. Definitely an odd case but problematic is that the indexing load circle never goes away and no error is shown outside of console.
Also error does not state the file name it died on specifically

Foundry: 11.311
Moulinette core: 11.4.0
moulinette scenes: 11.1.2

**Comment by SvenWerlen** [comment] 2023-11-05 16:35
Hi!
I was not able to reproduce the exact same issue on the latest release (Moulinette Core).
In my case, the indexing process works but Moulinette doesn't render the image correctly.
I can confirm that this is caused by having "%" in the filename.

**Comment by SvenWerlen** [comment] 2023-11-05 16:48
Fixed in Moulinette Core (`11.6.1`)

**Closed by SvenWerlen** 2023-11-05 16:48 UTC
