### ISSUE TITLE
Large image directory in S3

### ISSUE THREAD

**Issue by matt-duffy** [SvenWerlen/moulinette-core#6] opened 2021-04-30 14:17 UTC
Core Version: 0.7.9

System: dnd5e 1.2.4 (Atropos) 

moulinette-core 1.4.1 (Sven Werlen)
moulinette-gameicons 1.1.0 (Sven Werlen)
moulinette-imagesearch 1.3.0 (Sven Werlen)
moulinette-scenes 1.2.0 (Sven Werlen)
moulinette-sounds 1.1.0 (Sven Werlen)
moulinette-tiles 1.6.0 (Sven Werlen)

With a large image directory in S3 (for instance the entire map making pack from Forgotten Adventures) the indexing of the assets fails.  If I keep removing items it will eventually get to a point where the indexing works, but if I try to do it for the full set of items then it doesn't work.  No errors in the console, the message just never comes up to say it has finished and the index is not updated.

**Comment by SvenWerlen** [comment] 2021-05-04 01:21
I think that this issue is now fixed. It was caused by a strange issue in Foundry itself. I implemented a workaround to avoid the issue and people confirmed that large directories on S3 work now. Could you please update the core module and re-test?
I'll close this issue. Please re-open it if it's not fixed for you. Note that some people also mentioned that FVTT doesn't support well spaces in folder names.

**Closed by SvenWerlen** 2021-05-04 01:21 UTC

**Comment by matt-duffy** [comment] 2021-05-04 07:58
Yep working now, thanks!  I had a workaround of indexing on a local instance and then copying up the JSON, but it working on the server neatly is so much better, great module.
