### ISSUE TITLE
Thumbnails will not display if brackets are in file name

### ISSUE THREAD

**Issue by caewok** [SvenWerlen/moulinette-core#21] opened 2021-08-31 17:26 UTC
**Setup**
Foundry VTT 0.8.9
Moulinette Core 3.4.3
dnd5e 1.4.2
Files are stored in S3 (Backblaze)

**Issue**
If the file name for the image has brackets ("[" or "]"), the thumbnail will not display in Moulinette Tile picker UI. I tested by removing the brackets, in which case the file thumbnail displays fine. Note that this file is stored in S3.

**Comment by SvenWerlen** [comment] 2021-09-04 01:51
Thank you for reporting this. It seems to be related to S3 since this cannot reproduced locally
![image](https://user-images.githubusercontent.com/938060/132078597-981c0464-e708-4679-a74e-316f900b8073.png)

**Comment by SvenWerlen** [comment] 2021-09-04 01:56
Actually, even with S3, I'm not able to reproduce it. I might need more information about how to reproduce. 
Could you see errors in the console (Network tab)?

**Comment by SvenWerlen** [comment] 2021-10-11 21:23
Closing this issue (cannot be reproduced). Feel free to re-open it.

**Closed by SvenWerlen** 2021-10-11 21:23 UTC
