### ISSUE TITLE
After update, file picker no longer works

### ISSUE THREAD

**Issue by nirurin** [SvenWerlen/moulinette-core#59] opened 2023-01-31 22:48 UTC
ReferenceError: undefined. MoulinetteForge is not defined
[Detected 1 package: moulinette-core]

I write in my search term, hit enter (or the magnifying glass) but no results pop up. This error appears in the console. 
Worked fine yesterday, so it's something to do with a recent update. 

Edit: More information.
It doesn't work if it's on 'tile view' or 'thumbnail view', but if I put it on 'list view' results do come up.

**Comment by SvenWerlen** [comment] 2023-01-31 23:59
Can you share which versions of `moulinette-core`do you have?
I'm not able to reproduce the issue.

**Comment by SvenWerlen** [comment] 2023-02-01 00:46
Oh, I realized that it was related to the FilePicker, not the regular UI. I confirm then the bug.

**Comment by SvenWerlen** [comment] 2023-02-01 00:51
Fixed in `10.5.0

**Closed by SvenWerlen** 2023-02-01 00:51 UTC
