### ISSUE TITLE
Spaces in folder names break asset search

### ISSUE THREAD

**Issue by Akaito** [SvenWerlen/moulinette-core#38] opened 2022-04-05 01:22 UTC
I'm using an S3 bucket, a custom root path ("assets/"), and have found that having spaces in folder names confuses Moulinette's search.  Because it's comparing a URL-encoded string with a "normal" string.  Example from its debug messages:

`Moulinette FileUtil | Assets: ignoring assets/venatus-maps/Swamp Assets/Dead Trees which is NOT a subfolder of assets/venatus-maps/Swamp%20Assets as expected!`

Note the Swamp Assets is a silly attempt on my part, as I just realized it's already included in Moulinette (guessing due to Patreon membership and linking).  But, the bug still stands that Moulinette should be comparing either URL-encoded to URL-encoded, or "normal" to "normal".  Not one to the other.

**Comment by SvenWerlen** [comment] 2022-04-09 16:26
I'm not able to reproduce this issue. I tested a custom path on S3 and a folder name with space. 
Everything gets indexed and I can see it in moulinette.

Could you please provide more information ?
* What is the action which triggers the above error (search, indexing, etc.)?
* Which version of moulinette core do you use?

**Comment by SvenWerlen** [comment] 2022-05-15 14:12
Closing this issue. Cannot reproduce it. Feel free to re-open it with the requested additional information.

**Closed by SvenWerlen** 2022-05-15 14:12 UTC
